### ISSUE TITLE
Doesn't handle surrogate pairs correctly

### ISSUE THREAD

**Issue by gc** [kyranet/levenshtein-wasm#8] opened 2019-05-31 08:50 UTC
`levenshteinWasm('K̇yra', 'Kyra');` returns 2 when it should return 1.

I tested 3 other js levenshtein implementations and they return 1. 

Reproduction:
`git clone https://github.com/gc/leven-repro.git`

```js
const levenshteinWasm = require('levenshtein-wasm').levenshtein;
const jsLevenshtein = require('js-levenshtein');
const fastLevenshtein = require('fast-levenshtein').get;
const leven = require('leven');

function compare(x, y) {
    console.log('levenshteinWasm ' + levenshteinWasm(x, y)); // 2
    console.log('jsLevenshtein ' + jsLevenshtein(x, y)); // 1
    console.log('fastLevenshtein ' + fastLevenshtein(x, y)); // 1
    console.log('leven ' + leven(x, y)); // 1
}

compare('K̇yra', 'Kyra');
```

EDIT: its a diacritic mark and not a surrogate pair, its still not as expected however

**Comment by kyranet** [comment] 2019-05-31 09:36
While I can reproduce this, I suspect this is one complicated bug... since that character is composed of 3 (which would be an `Uint24`, and that doesn't exist, plus strings are `Uint16Array`s...):

```javascript
const u8 = new TextEncoder().encode('K̇');
console.log(u8); // -> Uint8Array [ 75, 204, 135 ]
```

How do the other libraries handle emojis? `😀` is composed by 2 UTF-16 characters, and its length in JavaScript is 2, just like the `K̇` unicode character.

**Comment by kyranet** [comment] 2019-06-07 07:35
Resolved in https://github.com/kyranet/levenshtein-wasm/commit/7c86572b182aafc1777fd70d76940577b3452f61

```
PS D:\Repositories\Libraries\levenshtein-wasm> node
> require('./').levenshtein('K̇yra', 'Kyra');
1
```

**Closed** 2019-06-07 07:35 UTC
Labels: bug
